# Generated by Django 6.0.5 on 2026-06-05 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=50)),
                ('action_type', models.CharField(blank=True, max_length=50, null=True)),
                ('entity_name', models.CharField(blank=True, max_length=50, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user'], name='users_usera_user_id_269a60_idx'), models.Index(fields=['event_type'], name='users_usera_event_t_d9907f_idx'), models.Index(fields=['created_at'], name='users_usera_created_828ca1_idx')],
            },
        ),
    ]
