# Generated by Django 6.0.5 on 2026-06-10 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='useractivity',
            name='users_usera_user_id_269a60_idx',
        ),
        migrations.RemoveIndex(
            model_name='useractivity',
            name='users_usera_event_t_d9907f_idx',
        ),
        migrations.RemoveIndex(
            model_name='useractivity',
            name='users_usera_created_828ca1_idx',
        ),
        migrations.DeleteModel(
            name='UserActivity',
        ),
    ]
