# Generated by Django 6.0.5 on 2026-05-20 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='cover_letter',
            field=models.TextField(blank=True),
        ),
    ]
