# Generated by Django 6.0.5 on 2026-06-08 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('event_type', models.CharField(max_length=50)),
                ('action_type', models.CharField(blank=True, max_length=50, null=True)),
                ('entity_name', models.CharField(blank=True, max_length=50, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['user_id'], name='activity_us_user_id_412a5e_idx'), models.Index(fields=['event_type'], name='activity_us_event_t_f357d4_idx'), models.Index(fields=['created_at'], name='activity_us_created_011506_idx')],
            },
        ),
    ]
