# Generated by Django 6.0.5 on 2026-06-10 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_alter_useractivity_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='entity_id',
            field=models.IntegerField(blank=True, max_length=50, null=True),
        ),
    ]
