# Generated by Django 6.0.5 on 2026-06-10 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_useractivity_entity_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='entity_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
