# Generated by Django 6.0.5 on 2026-06-10 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_alter_useractivity_entity_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractivity',
            name='entity_id',
        ),
    ]
